name: curreny_labs
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
    # Flutter widgets implementing the current iOS design language(default dependency)
  cupertino_icons: ^1.0.8
  # easy to integrate blocs and cubits into Flutter
  flutter_bloc: ^8.1.6
  # automatically persists and restores bloc and cubit states
  hydrated_bloc: ^9.1.5
  # exposes custom event transformers
  bloc_concurrency: ^0.2.5
  # Service locator
  get_it: ^8.0.2
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  # Generating copyWith extensions for classes
  copy_with_extension: ^5.0.3
  # A collection of utilities to transform and manipulate streams.
  stream_transform: ^2.1.0
  # Easy and Fast internationalizing and localization your Flutter Apps
  easy_localization: ^3.0.7
  # Flutter plugin for Firebase Core, enabling connecting to multiple Firebase apps.
  firebase_core: ^3.8.0
  # Flutter plugin for Firebase Auth, enabling authentication using passwords, phone numbers and identity providers like Google, Facebook and Twitter.
  firebase_auth: ^5.3.3
  # Flutter plugin for Firebase Database, a cloud-hosted NoSQL database with realtime data syncing across Android and iOS clients, and offline access.
  firebase_database: ^11.1.6
  # Flutter plugin for Firebase Cloud Storage, a powerful, simple, and cost-effective object storage service for Android and iOS.
  firebase_storage: ^12.3.6
  # The easiest way to add facebook login to your flutter app. Feature includes getting user information, profile picture and more. This plugin also supports Web and macOS.
  flutter_facebook_auth: ^7.1.1
  # Flutter plugin for Google Sign-In, a secure authentication system for signing in with a Google account.
  google_sign_in: ^6.2.2
  # simplify form representation and validation in a generic way.
  formz: ^0.8.0
  # finding commonly used locations on the filesystem
  path_provider: ^2.1.5
  # check for an Active Internet connection
  internet_connection_checker: ^1.0.0+1
  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.19.0
  # A powerful HTTP networking package for Dart/Flutter
  dio: ^5.7.0
  # Annotations for freezed
  freezed_annotation: ^2.4.1
  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android.
  package_info_plus: ^8.1.1
  # adapting screen and font size.Let your UI display a reasonable layout on different screen sizes
  flutter_screenutil: ^5.9.3
  # automatically resizes text to fit perfectly within its bounds
  auto_size_text: ^3.0.0
  # to show images from the internet and keep them in the cache directory
  cached_network_image: ^3.4.1
  # A clean and lightweight loading widget for Flutter, Easy to use without context
  flutter_easyloading: ^3.0.5
  # A simple widget to display image in a full-screen, swipe it to dismiss, pinch & zoom
  insta_image_viewer: ^1.0.4
  # Customize Flutter's default white native splash screen with background color and splash image.
  flutter_native_splash: ^2.4.2
  # Draw SVG files using Flutter
  flutter_svg: ^2.0.14
  # Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^1.1.2
  # A Flutter plugin for Android, iOS and Web supports cropping images
  image_cropper: ^8.0.2
  # UUID Generator and Parser for Dart
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  copy_with_extension_gen: ^5.0.3
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  background_image: "assets/images/splash.png"

  android_12:
    image: "assets/images/app_icon.png"
    color: "#ffffff"
    icon_background_color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/openSans/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/openSans/OpenSans-LightItalic.ttf
          weight: 300
        - asset: assets/fonts/openSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/openSans/OpenSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/openSans/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/openSans/OpenSans-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/openSans/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/openSans/OpenSans-SemiBoldItalic.ttf
          weight: 600
        - asset: assets/fonts/openSans/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/openSans/OpenSans-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/openSans/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/openSans/OpenSans-ExtraBoldItalic.ttf
          weight: 800
